__title__ = 'mend-junit-report'
__summary__ = 'Simple tool that converts a mend file to junit format'
__version__ = '2.1.0'
__uri__ = 'https://github.com/sede-x/mend-junit-report'
__author__ = 'Michelle A. Taal'
__email__ = 'michelletaal@shell.com'
